# documentation on https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions
name: python-testing

on: [push, pull_request]

jobs:
  python-testing:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6, 3.7, 3.8, 3.9]

    steps:
      - name: Check out the Repository
        uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Python dependencies
        run: |
          python --version
          python -m pip install --upgrade pip

      - name: Prepare Python Environment
        run: |
          pip install virtualenv
          virtualenv venv
          source venv/bin/activate

      - name: Install Software Requirements
        run: |
          pip install --upgrade setuptools
          pip install --upgrade coveralls
          pip install -r requirements.txt
          pip install .

      - name: Test using pytest
        run: |
          python3 setup.py pytest

      - name: Coveralls coverage upload
        run: |
          coveralls
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repository
        uses: actions/checkout@master

      - name: Run markdownlint (mdl)
        uses: bewuethr/mdl-action@master
        with:
          style-file: .github/workflows/markdownlint.rb

  shellcheck:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the Repository
        uses: actions/checkout@master

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@0.3.0
